version: "3"

services:
  backend:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: mysql
    hostname: mysqldb
    container_name: mysqldb
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306




#  mysqldb:
#    image: mysql:8.0
#    hostname: mysqldb
#    container_name: mysqldb
#    restart: always
##    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data:/var/lib/mysql
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
# #     MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: smarttourpe
#      MYSQL_USER: usertest
# #     MYSQL_PASSWORD: root