#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/smarttourpe?createDatabaseIfNotExist=true
#    username: root
#    password: root


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/smarttourpe?createDatabaseIfNotExist=true
    username: user
    password: pass





#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#  spring.datasource.username=springuser
#  spring.datasource.password=ThePassword
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.show-sql: true